# Generated by Django 4.2.16 on 2024-10-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_auto', models.CharField(max_length=20)),
                ('power', models.IntegerField()),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя покупателя(username аккаунта)')),
                ('balance', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Ваш баланс')),
                ('age', models.IntegerField(verbose_name='Ваш возраст')),
            ],
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_dogs', models.CharField(max_length=20)),
                ('name_dogs', models.CharField(max_length=20)),
                ('weight_dogs', models.IntegerField()),
            ],
        ),
    ]
